version: '3'

services:
  bazar:
    build: ./bazar
    ports:
      - "8080:8080"
    environment:
      DB_URL: jdbc:mysql://bazar_db:3306/bazar_db?createDatabaseIfNotExist=true&serverTimezone=UTC
      DB_USER: root
      DB_PASSWORD: 1234
      SS_USER: jcoronado
      SS_PASSWORD: 1234
    restart: always
    depends_on:
      bazar_db:
        condition: service_healthy

  bazar_db:
    image: mysql:8.0.33
    ports:
      - "3307:3306"
    environment:
      MYSQL_ROOT_PASSWORD: 1234
      MYSQL_DATABASE: bazar_db
    restart: always
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost"]
      timeout: 10s
      retries: 10